version: "2"
services:
  privnet-1:
    image: effectai/neo-node:2.7.3
    tty: true
    ports:
      - 30333:10333
      - 10332:10332
    volumes:
      - ./wallets/wallet1.json:/opt/wallet.json
    environment:
      - WALLET_PASS=one
  privnet-2:
    image: effectai/neo-node:2.7.3
    tty: true
    ports:
      - 30334:10333
    volumes:
      - ./wallets/wallet2.json:/opt/wallet.json
    environment:
      - WALLET_PASS=two
  privnet-3:
    image: effectai/neo-node:2.7.3
    tty: true
    volumes:
      - ./wallets/wallet3.json:/opt/wallet.json
    ports:
      - 30335:10333
    environment:
      - WALLET_PASS=three
  privnet-4:
    image: effectai/neo-node:2.7.3
    tty: true
    ports:
      - 30336:10333
    volumes:
      - ./wallets/wallet4.json:/opt/wallet.json
    environment:
      - WALLET_PASS=four
  # Duplo
  duplo-backend:
    image: effectai/neo-clojure-clr:latest
    ports:
      - 10336:10336
    command: tasks/rpc
    volumes:
      - /usr/local/neo-clj/data
    environment:
      - RPC_SERVER=http://privnet-1:10332
      - DATA_DIR=/usr/local/neo-clj/data
  duplo:
    image: effectai/duplo
    ports:
      - 8080:80
