version: "2"
services:
  privnet-1:
    build: .
    tty: true
    ports:
      - 10332:10332
    environment:
      - CONSENSUS_KEY=KxyjQ8eUa4FHt3Gvioyt1Wz29cTUrE4eTqX3yFSk1YFCsPL8uNsY
  privnet-2:
    build: .
    tty: true
    environment:
      - CONSENSUS_KEY=KzfPUYDC9n2yf4fK5ro4C8KMcdeXtFuEnStycbZgX3GomiUsvX6W
  privnet-3:
    build: .
    tty: true
    environment:
      - CONSENSUS_KEY=L2oEXKRAAMiPEZukwR5ho2S6SMeQLhcK9mF71ZnF7GvT8dU4Kkgz
  privnet-4:
    build: .
    tty: true
    environment:
      - CONSENSUS_KEY=KzgWE3u3EDp13XPXXuTKZxeJ3Gi8Bsm8f9ijY3ZsCKKRvZUo1Cdn

